version: '3'

services:
  nextapp:
    extends:
      file: ./nextapp/docker-compose.yml
      service: nextapp
    networks:
      - WebApp

  fastapi:
    extends:
      file: ./fastapi/docker-compose.yml
      service: fastapi
    networks:
      - WebApp

networks:
  WebApp:
    driver: bridge
  